version: '3.7'

services:
  nodejsvoiceapp:
    build:
      context: .  
    image: fonoster/nodejsvoiceapp:latest
    restart: always
    ports:
      - 5000:5000
    environment:
      LOGS_LEVEL: verbose
      # Uncomment the following line to enable fluent transport
      # LOGS_TRANSPORT: fluent
